Repository pvlib/pvanalytics, pull requests merged in 2022-08, with the labels that each got.

#131 Added sphinx documentation for data shifts routine.
  .readthedocs.yml
  docs/examples/data-shifts.py
  docs/whatsnew/0.1.2.rst
Labels: documentation

#149 Delete requirements.txt; related CI & test changes
  .github/workflows/lint-and-test.yml
  docs/index.rst
  pvanalytics/tests/quality/test_data_shifts.py
  requirements.txt
  setup.py
Labels: ci

#148 Orientation sphinx documentation
  docs/examples/fixed-nrel.py
  docs/examples/tracking-nrel.py
  docs/whatsnew/0.1.2.rst
  pvanalytics/data/nrel_1axis_tracker_mesa_ac_power.csv
  pvanalytics/data/serf_east_15min_ac_power.csv
Labels: documentation

#145 Miscellaneous doc and module cleanup
  README.md
  docs/index.rst
  docs/whatsnew/0.1.2.rst
  pvanalytics/__init__.py
  pvanalytics/filtering.py
  pvanalytics/fitting/__init__.py
  pvanalytics/fitting/temperature.py
Labels: documentation

#150 v0.1.2 Release
  docs/whatsnew/0.1.2.rst
  docs/whatsnew/0.1.3.rst
  docs/whatsnew/index.rst
Labels: release
