Repository pvlib/pvanalytics, pull requests merged in 2022-01, with the labels that each got.

#118 Update pandas requirements
  .github/workflows/lint-and-test.yml
  docs/whatsnew/0.1.1.rst
  requirements.txt
  setup.py
Labels: dependency

#114 Small improvements to sphinx docs
  docs/conf.py
  pvanalytics/features/clipping.py
  pvanalytics/features/shading.py
  pvanalytics/quality/gaps.py
  pvanalytics/quality/irradiance.py
  pvanalytics/quality/outliers.py
  pvanalytics/quality/time.py
  pvanalytics/quality/weather.py
  pvanalytics/system.py
  setup.py
Labels: documentation

#120 Updated the polyfit function to np.polynomial.Polynomial.fit()
  pvanalytics/util/_fit.py
Labels: dependency

#128 Get clearsky.reno tests passing again
  docs/whatsnew/0.1.1.rst
  pvanalytics/features/clearsky.py
  pvanalytics/tests/features/test_clearsky.py
Labels: bug, tests
