Repository pvlib/pvanalytics, pull requests merged in 2022-12, with the labels that each got.

#146 System module sphinx documentation
  docs/examples/system/README.rst
  docs/examples/system/infer-orientation-fit-pvwatts.py
  docs/examples/system/system-tracking.py
  docs/whatsnew/0.1.2.rst
  docs/whatsnew/0.1.3.rst
  pvanalytics/data/serf_east_15min_ac_power.csv
  pvanalytics/data/serf_east_psm3_data.csv
Labels: documentation

#177 v0.1.3 release
  LICENSE
  docs/conf.py
  docs/index.rst
  docs/whatsnew/0.1.3.rst
  docs/whatsnew/0.1.4.rst
  docs/whatsnew/index.rst
Labels: release

#179 Advance minimum pvlib to 0.9.4, and attendant cleanup
  docs/whatsnew/0.1.4.rst
  docs/whatsnew/index.rst
  pvanalytics/quality/irradiance.py
  pvanalytics/tests/features/test_clearsky.py
  pvanalytics/tests/features/test_orientation.py
  pvanalytics/tests/test_pvanalytics.py
  pvanalytics/tests/test_system.py
  requirements-min.txt
  setup.py
Labels: dependency
