Repository pvlib/pvanalytics, pull requests merged in 2023-01, with the labels that each got.

#180 Updated to PVWatts5 methodology in the pvwatts orientation estimation function system.infer_orientation_fit_pvwatts()
  docs/whatsnew/0.1.4.rst
  pvanalytics/system.py
Labels: enhancement

#181 Fix `pvanalytics.__version__`
  docs/whatsnew/0.1.4.rst
  pvanalytics/__init__.py
  pvanalytics/tests/test_pvanalytics.py
  setup.py
Labels: bug

#178 Switch docs to pydata-sphinx-theme
  .github/pull_request_template.md
  README.md
  docs/conf.py
  docs/examples/weather/weather-limits.py
  docs/index.rst
  docs/whatsnew/0.1.4.rst
  pvanalytics/quality/irradiance.py
  setup.py
Labels: documentation

#182 What's new cleanup for v0.2.0-alpha.1
  .github/workflows/pythonpublish.yml
  docs/whatsnew/0.2.0.rst
  docs/whatsnew/index.rst
Labels: release
