Repository pvlib/pvanalytics, pull requests merged in 2024-02, with the labels that each got.

#192 Create gallery page for `shifts_ruptures`
  docs/examples/data-shifts/README.rst
  docs/examples/shifts/README.rst
  docs/examples/shifts/data-shifts.py
  docs/examples/shifts/shifts-ruptures.py
  docs/whatsnew/0.2.0.rst
Labels: documentation

#203 Address various deprecations and test issues with pandas 2.2.0
  docs/examples/clipping/clipping.py
  docs/examples/day-night-masking/day-night-masking.py
  docs/examples/gaps/data-completeness.py
  docs/examples/gaps/stale-data.py
  docs/examples/irradiance-quality/clearsky-limits-irradiance.py
  docs/examples/metrics/variability-index.py
  docs/examples/system/infer-orientation-fit-pvwatts.py
  docs/examples/system/system-tracking.py
  docs/examples/weather/module-temperature-check.py
  docs/whatsnew/0.2.0.rst
  pvanalytics/features/clearsky.py
  pvanalytics/features/clipping.py
  pvanalytics/quality/gaps.py
  pvanalytics/quality/outliers.py
  pvanalytics/system.py
  pvanalytics/tests/conftest.py
  pvanalytics/tests/features/test_clearsky.py
  pvanalytics/tests/features/test_clipping.py
  pvanalytics/tests/features/test_daytime.py
  pvanalytics/tests/features/test_orientation.py
  pvanalytics/tests/features/test_shading.py
  pvanalytics/tests/quality/test_gaps.py
  pvanalytics/tests/quality/test_irradiance.py
  pvanalytics/tests/quality/test_time.py
  pvanalytics/tests/quality/test_util.py
  pvanalytics/tests/quality/test_weather.py
  pvanalytics/tests/test_system.py
Labels: dependency, tests

#204 Add Python 3.12 to test matrix
  .github/workflows/lint-and-test.yml
  docs/whatsnew/0.2.0.rst
  pvanalytics/tests/conftest.py
  pvanalytics/tests/test_pvanalytics.py
  setup.py
Labels: ci, tests

#206 Allow tz-aware timstamps in `gaps.trim`
  docs/whatsnew/0.2.0.rst
  pvanalytics/quality/gaps.py
  pvanalytics/tests/quality/test_gaps.py
Labels: bug

#202 Added PV Fleets QA pipeline examples
  docs/examples/pvfleets-qa-pipeline/README.rst
  docs/examples/pvfleets-qa-pipeline/pvfleets-irradiance-qa.py
  docs/examples/pvfleets-qa-pipeline/pvfleets-power-qa.py
  docs/examples/pvfleets-qa-pipeline/pvfleets-temperature-qa.py
  docs/whatsnew/0.2.0.rst
  pvanalytics/data/system_15_poa_irradiance.parquet
  pvanalytics/data/system_4_module_temperature.parquet
  pvanalytics/data/system_50_ac_power_2_full_DST.parquet
  pvanalytics/data/system_50_ac_power_2_full_DST_psm3.parquet
  setup.py
Labels: documentation

#205 Advance minimum scipy to 1.6
  docs/whatsnew/0.2.0.rst
  pvanalytics/quality/irradiance.py
  requirements-min.txt
  setup.py
Labels: dependency

#207 Finalize v0.2.0
  docs/whatsnew/0.2.0.rst
Labels: release
