Repository pvlib/pvanalytics, pull requests merged in 2024-10, with the labels that each got.

#209 Code and example for classifying snow effects
  docs/api.rst
  docs/examples/snow-detection/README.rst
  docs/examples/snow-detection/snow-mode.py
  docs/index.rst
  docs/whatsnew/0.2.1.rst
  pvanalytics/data/snow_data.csv
  pvanalytics/data/snow_snowfall.csv
  pvanalytics/features/snow.py
  pvanalytics/tests/features/test_snow.py
Labels: enhancement, feature

#216 Finalize v0.2.1
  docs/whatsnew/0.2.1.rst
  docs/whatsnew/0.2.2.rst
  docs/whatsnew/index.rst
Labels: release

#214 Add outside_domain parameter to irradiance ratio QC tests
  docs/whatsnew/0.2.2.rst
  pvanalytics/quality/irradiance.py
  pvanalytics/tests/quality/test_irradiance.py
Labels: enhancement

#190 Add extreme QCRAD QC limits
  docs/whatsnew/0.2.2.rst
  pvanalytics/quality/irradiance.py
  pvanalytics/tests/quality/test_irradiance.py
Labels: enhancement
